#!/bin/bash

# bixby post-install script

url="https://s3.bixby.io"

function bootstrap_repo() {
  if [ -d /opt/bixby/repo ]; then
    return 0;
  fi

  # fix ownership - I think fpm should handle this but this is easier for now
  chown -R root:root /opt/bixby

  cd /opt/bixby
  mkdir repo
  cd repo
  ver=`\\curl -sL $url/latest-repo`
  pkg="repo-$ver.tar.gz"
  wget $url/$pkg
  tar -xzf $pkg
  mv bixby-repo vendor
  rm -f $pkg

  return 0
}

function is_registered {
  [[ -f /opt/bixby/etc/bixby.yml && -f /opt/bixby/etc/server.pub ]]
}

function upgrade_bixby() {
  if [[ ! -f /etc/init.d/bixby ]]; then
    # install init script
    cd /opt/bixby
    mv etc/bixby-god.initd /etc/init.d/bixby
    chmod 755 /etc/init.d/bixby
    # if is_registered; then
    #   /opt/bixby/bin/bixby-agent stop
    # fi
  fi

  # restart service using bixby
  # if is_registered; then
  #   /etc/init.d/bixby restart
  # fi
}

bootstrap_repo || exit 1

upgrade_bixby
