#!/bin/bash

# bixby post-install script

url="https://s3.bixby.io"

function bootstrap_repo() {
  if [ -d /opt/bixby/repo ]; then
    return 0;
  fi

  cd /opt/bixby
  mkdir repo
  cd repo
  ver=`\\curl -sL $url/latest-repo`
  pkg="repo-$ver.tar.gz"
  wget $url/$pkg
  tar -xzf $pkg
  mv bixby-repo vendor
  rm -f $pkg

  return 0
}

bootstrap_repo || exit 1
