#!/bin/bash

# bixby post-install script

url="https://s3.bixby.io"

BIXBY_HOME=/opt/bixby

function bootstrap_repo() {
  if [ -d /opt/bixby/repo ]; then
    return 0;
  fi

  cd $BIXBY_HOME
  mkdir repo
  cd repo
  ver=`\\curl -sL $url/latest-repo`
  pkg="repo-$ver.tar.gz"
  wget $url/$pkg
  tar -xzf $pkg
  mv bixby-repo vendor
  rm -f $pkg

  return 0
}

function is_registered {
  [[ -f $BIXBY_HOME/etc/bixby.yml && -f $BIXBY_HOME/etc/server.pub ]]
}

function upgrade_bixby() {
  if [[ ! -f /etc/init.d/bixby ]]; then
    # install init script & god confs
    cd $BIXBY_HOME
    cd $(readlink -f $(dirname $(embedded/bin/gem which bixby-agent))/..)

    cp -a etc/bixby-god.initd /etc/init.d/bixby
    chmod 755 /etc/init.d/bixby

    mkdir -p $BIXBY_HOME/etc
    cp -a etc/bixby.god etc/god.d $BIXBY_HOME/etc/
    cd $BIXBY_HOME

    # if is_registered; then
    #   /opt/bixby/bin/bixby-agent stop
    # fi
  fi

  # restart service using bixby
  # if is_registered; then
  #   /etc/init.d/bixby restart
  # fi
}

bootstrap_repo

# fix ownership of bixby paths
chown bixby:bixby $BIXBY_HOME
chown bixby:bixby $BIXBY_HOME/*
chown -R bixby:bixby $BIXBY_HOME/bin
chown -R bixby:bixby $BIXBY_HOME/embedded
chown -R bixby:bixby $BIXBY_HOME/repo

upgrade_bixby
